backend:
  name: git-gateway
  repo: github.com/kevinctofel/gatsby
  branch: master # Branch to update (optional; defaults to master)
  squash_merges: true

media_folder: "static/images/uploads"
public_folder: "/images/uploads"
media_library:
  name: images

publish_mode: editorial_workflow

site_url: https://www.kctofel.com

collections:
  - name: posts
    label: Blog Posts
    folder: posts
    create: true
    fields:
      - { name: tags, label: Tags, widget: list, required: false }
      - { name: published, label: Published, widget: boolean }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
